### ISSUE TITLE
Error shows Nodejs 12.x is needed

### ISSUE THREAD

**Issue by aldoyh** [juicyfx/vercel-examples#103]
# Bug report

Just right after cloning the git I ran `vercel`
And this is my output:

![Screenshot 2022-10-29 at 12 01 56 AM](https://user-images.githubusercontent.com/5215449/198733040-70cf9aa6-3f43-4fc5-866c-75f01ab71c17.jpg)

Otherwise, amazing work!

**Comment by TheunisKotze** [comment]
Yup the version in the example project just needs to be bumped to the latest  eg 
`
{
  "functions": {
    "api/index.php": {
      "runtime": "vercel-php@0.5.2"
    }
  }
}
`

**Comment by aldoyh** [comment]
> Yup the version in the example project just needs to be bumped to the latest eg `{ "functions": { "api/index.php": { "runtime": "vercel-php@0.5.2" } } }`

I checked and it is actually the latest version now.

**Comment by alphaolomi** [comment]
+1

```
Error: The Runtime "vercel-php@0.3.1" is using "nodejs12.x", which is discontinued. 
Please upgrade your Runtime to a more recent version or consult the author for more details.
```

**Comment by f3l1x** [comment]
@alphaolomi Please use 0.5.x release.

**Comment by f3l1x** [comment]
Hi, can you folks try new versions?

vercel-php@0.6.0 - PHP 8.2.x (https://example-php-8-2.vercel.app/)
vercel-php@0.5.3 - PHP 8.1.x (https://example-php-8-1.vercel.app/)
vercel-php@0.4.1 - PHP 8.0.x (https://example-php-8-0.vercel.app/)
vercel-php@0.3.3 - PHP 7.4.x (https://example-php-7-4.vercel.app/)
