### ISSUE TITLE
[laravel] could not find driver with sqlite3

### ISSUE THREAD

**Issue by AGDholo** [juicyfx/vercel-examples#15]
# Bug report

- Example: No
- URL:No
- Repository: No

## Description

I set the DB drive config to `sqlite` , 

`.env`:
DB_CONNECTION=sqlite
DB_DATABASE=D:\repo\php-laravel\database\database.sqlite

or

`now.json`:
"DB_CONNECTION": "sqlite",
"DB_DATABASE": "D:\repo\php-laravel\database\database.sqlite"

But the console told me the warning when I use the `php artisan migrate` command: 
```text
Illuminate\Database\QueryException 

could not find driver (SQL: select * from information_schema.tables where table_schema = forge and 
table_name = migrations and table_type = 'BASE TABLE')
```

I can use sqlite as a database in a brand new laravel application.

**Comment by reed-jones** [comment]
I don't think `D:\repo\php-laravel\database\database.sqlite` is a valid path on vercel. As far as I know, only the `/tmp` directory is writable, and looking at the [sqlite example](https://github.com/juicyfx/vercel-examples/blob/master/php-sqlite/api/index.php) seems to confirm that hunch for me...

**Comment by AGDholo** [comment]
@reed-jones 
I am not available for local debugging.

**Comment by reed-jones** [comment]
sorry I can't be much more help, I generally don't use sqlite or windows for development

**Comment by f3l1x** [comment]
Hey. Path to sqlite db file must pointing to `/tmp` folder. This is only writable folder in labmda.

**Comment by f3l1x** [comment]
Closing here.

https://github.com/juicyfx/vercel-examples/blob/c156c02feb4e8f8677913d99aedaceb164828436/php-sqlite/api/index.php#L1-L20
