### ISSUE TITLE
Error with Symfony

### ISSUE THREAD

**Issue by damienmillet** [juicyfx/vercel-examples#16]
# Bug report

- Example: https://grabby.vercel.app
- URL:  No
- Repository: Yes https://github.com/CrabThug/grabby

## Description

`Fatal error: Uncaught RuntimeException: Unable to create the "cache" directory (/var/task/user/var/cache/prod). in /var/task/user/vendor/symfony/http-kernel/Kernel.php:623 Stack trace: #0 /var/task/user/vendor/symfony/http-kernel/Kernel.php(532): Symfony\Component\HttpKernel\Kernel->buildContainer() #1 /var/task/user/vendor/symfony/http-kernel/Kernel.php(131): Symfony\Component\HttpKernel\Kernel->initializeContainer() #2 /var/task/user/vendor/symfony/http-kernel/Kernel.php(191): Symfony\Component\HttpKernel\Kernel->boot() #3 /var/task/user/public/index.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #4 /var/task/user/api/index.php(3): require('/var/task/user/...') #5 {main} thrown in /var/task/user/vendor/symfony/http-kernel/Kernel.php on line 623`

**Comment by rolandihms** [comment]
If I am not mistaken, you can only write to the /tmp/ directory. Try setting your cache path. 
[https://symfony.com/doc/current/configuration/override_dir_structure.html#override-the-cache-directory](https://symfony.com/doc/current/configuration/override_dir_structure.html#override-the-cache-directory)

**Comment by damienmillet** [comment]
Perfect ! thx for ur rapidity,
the kernel file must be updated.
