### ISSUE TITLE
[laravel] Blade template compiling not saving in tmp folder

### ISSUE THREAD

**Issue by robertdrakedennis** [juicyfx/vercel-examples#19]
# Bug report

- Example: N/A
- URL: https://vercel-examples-lilac.vercel.app/
- Repository: [https://gitlab.com/xtlas/vercel-examples](https://gitlab.com/xtlas/vercel-examples)

## Description

```file_put_contents(/tmp/views/0f90093f751a3f4d993fa01cf5fee7b3bb0734ca.php): failed to open stream: No such file or directory```

I'm unsure if blades in general aren't supported, but I'm trying to have blades compile instead of using a SPA. Here's my now.json conifg:

```
{
  "version": 2,
  "functions": {
    "api/index.php": {
      "runtime": "vercel-php@0.3.1"
    }
  },
  "routes": [
        {
            "src": "/(.*)",
            "dest": "/api/index.php"
        }
  ],
  "env": {
    "APP_NAME": "Vercel Laravel",
    "APP_KEY": "REDACTED",
    "APP_ENV": "local",
    "APP_DEBUG": "true",
    "APP_URL": "https://php-laravel.vercel.app",
    "VERCEL_DEMO_MODE": "true",
    "APP_CONFIG_CACHE": "/tmp/config.php",
    "APP_EVENTS_CACHE": "/tmp/events.php",
    "APP_PACKAGES_CACHE": "/tmp/packages.php",
    "APP_ROUTES_CACHE": "/tmp/routes.php",
    "APP_SERVICES_CACHE": "/tmp/services.php",
    "CACHE_DRIVER": "array",
    "LOG_CHANNEL": "stderr",
    "SESSION_DRIVER": "array",
    "VIEW_COMPILED_PATH": "/tmp/views",
    "SSR_TEMP_PATH": "/tmp/ssr",
    "NODE_PATH": "node"
  }
}
```

**Comment by f3l1x** [comment]
Hey @robertdrakedennis. It looks like /tmp/views/ is not created, could you please test it and create it in init/bootstrap?

**Comment by robertdrakedennis** [comment]
Can you elaborate on what you mean by init/bootstrap? Are you wanting me to create the folders at runtime if they do not exist?

**Comment by f3l1x** [comment]
Yep, exactly. I am not laravel pro, so I don't know which file is the one.

**Comment by robertdrakedennis** [comment]
solved with a quick hack but could probably be added in a readme or something:

```
    if (!file_exists('/tmp/cache')) {
        mkdir('/tmp/cache');
    }

    if (!file_exists('/tmp/cache/data')) {
        mkdir('/tmp/cache/data');
    }

    if (!file_exists('/tmp/sessions')) {
        mkdir('/tmp/sessions');
    }

    if (!file_exists('/tmp/testing')) {
        mkdir('/tmp/testing');
    }

    if (!file_exists('/tmp/views')) {
        mkdir('/tmp/views');
    }

```

**Comment by f3l1x** [comment]
I am glad it works @robertdrakedennis. I thought Laravel can create these kind of folders automatically.
