### ISSUE TITLE
Setup Laravel

### ISSUE THREAD

**Issue by xRealNeon** [juicyfx/vercel-examples#20]
# Question

Hi what do I have to do to deploy my existing project on vercel?

**Comment by f3l1x** [comment]
Hi, take a look at laravel example (https://github.com/juicyfx/vercel-examples/tree/master/php-laravel). You need to download `vercel` package (https://vercel.com/download), account and then, call `vercel` in laravel folder. It should be enought. :-)

**Comment by xRealNeon** [comment]
In my existing application i only need to run vercel?

**Comment by f3l1x** [comment]
Well, in ideal world yes, but I think you gonna needed some updates, such as set path to /tmp folders, etc. I will try to put this info into the doc.

**Comment by xRealNeon** [comment]
And did you write a doc?

**Comment by f3l1x** [comment]
I have updated my laravel example. Please take a look at source code.
