### ISSUE TITLE
Laravel example not loading css / js files correctly on vercel

### ISSUE THREAD

**Issue by LarsWiegers** [juicyfx/vercel-examples#24]
# Bug report

- Example: Laravel
- URL: Yes https://test-project-virid.vercel.app/
- Repository: https://github.com/LarsWiegers/vercel-examples

## Description
Tried to deploy the laravel example, using the button on the right in the table.
Do not change any settings during deployment.
Get a page with html, but the css and js cant be loaded by vercel it gets a laravel 404 when trying to load them.

Would expect a html, css and js to be loaded.

**Comment by shiftenterdev** [comment]
Same issue for me 😢

**Comment by f3l1x** [comment]
Thank you guys. I promise I will take a look.

**Comment by f3l1x** [comment]
Fixed, https://github.com/juicyfx/vercel-examples/commit/0f1ee573d3cb01fecd70cc1e7b2977f0dfaaeb28

https://php-laravel.vercel.app/

<img width="1172" alt="Screenshot 2020-11-20 at 21 42 40" src="https://user-images.githubusercontent.com/538058/99848026-55799280-2b79-11eb-8b01-7ae8600b4675.png">
