### ISSUE TITLE
Wordpress cannot work

### ISSUE THREAD

**Issue by wizos** [juicyfx/vercel-examples#39]
# Bug report

- Example: wordpress
- URL: Yes (http://wordpress-alpha.vercel.app/)
- Repository: Yes

## Description

Redirect constantly between http://wordpress-alpha.vercel.app/wp-admin/install.php and https://wordpress-alpha.vercel.app/wp-admin/install.php

**Comment by f3l1x** [comment]
Yep, wordpress is not ready for serverless from my point of view.

**Comment by Abraham-Flutterwave** [comment]
is this in the works ?
