### ISSUE TITLE
How to use Cache::set('key', 'test'); with CACHE_DRIVER=file?

### ISSUE THREAD

**Issue by guoxiangke** [juicyfx/vercel-examples#75]
How to use Cache::set('key', 'test'); with CACHE_DRIVER=file?
I change to /tmp/ , no errors, but the cache function seems not work. each trigger always fetch from DB.
```
        'file' => [
            'driver' => 'file',
            'path' => storage_path('framework/cache/data'),
        ],
```
==>
```
        'file' => [
            'driver' => 'file',
            'path' => '/tmp/framework/cache/data',
        ],

```
thanks.

**Comment by f3l1x** [comment]
Hey. I don't know what is Cache::set. Generally, only /tmp folder is writable. You can test it with pure file_get_contents/file_put_contents.
