### ISSUE TITLE
API Platform / Symfony 6 API workaround

### ISSUE THREAD

**Issue by MaksOuw** [juicyfx/vercel-examples#95]
Hello, I encounter a problem with API Platform and Vercel, I tried many things and nothing seems to work.

What I have :
- API Platform project, based on Symfony 6
- `api` folder created to allow serverless function on Vercel (the `index.php` file contains the exact same thing as the `public/index.php` file)
- `vercel.json` with the following content : 
```json
{
    "functions": {
      "api/index.php": {
        "runtime": "vercel-php@0.5.2"
      }
    },
    "routes": [
      { "src": "/bundles/(.*)", "dest": "/public/bundles/$1" },
      { "src": "/(.*)", "dest": "/api/index.php" },
      { "src": "/api/(.*)", "dest": "/api/index.php" }
    ],
    "env": {
      "APP_ENV": "dev",
      "APP_SECRET": "b2b9b5f9ae35ad900c9c25605e210aad"
    }
}
``` 

When I try to access SwaggerUI (on `myurl.vercel.app/api`, it's kinda working (no assets but I know why and won't fix it since SwaggerUI won't go in production), but when I try to request the API, it just returns `No route found`.

I don't know what I'm doing wrong, but it's driving me crazy. Can you help me please ?

Thanks !

**Comment by MaksOuw** [comment]
Ok I found out how to fix my problem : change the prefix from `/api` to `/back` or any other things which is not `/api` and it'll work.

**Comment by f3l1x** [comment]
Hi @MaksOuw. It's weird, I think it should work without troubles. I will test it by my own.
